# Netlify configuration for ANKIDEMO
[build]
  publish = "."

# Redirect 404 errors to START_HERE.html
[[redirects]]
  from = "/*"
  to = "/START_HERE.html"
  status = 404

# Redirect root to START_HERE.html
[[redirects]]
  from = "/"
  to = "/START_HERE.html"
  status = 301

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache HTML files for immediate updates
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache static assets for better performance
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Enable form submissions (if you add forms later)
[build.environment]
  NODE_VERSION = "18"
